In [2]:
import numpy as np

# Question - 1

In [4]:
arr = np.arange(2, 50, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question - 2

In [10]:
lst1 = []
lst2 = []

for i in range(5):
    a = int(input("\nEnter the required number for the first list: "))
    lst1.append(a)
    
for i in range(5):
    a = int(input("\nEnter the required number for the Second list: "))
    lst2.append(a)
    
arr1 = np.array(lst1)
arr2 = np.array(lst2)

arr = np.concatenate((arr1, arr2))
print("\n\nConcatenated Array of Entered Array:" , arr)

sarr1 = np.sort(arr1)
sarr2 = np.sort(arr2)
sarr = np.sort(arr)

print("\n\nSorted Array :" ,"\nArray 1 :", sarr1, "\nArray 2 :", sarr2, "\nConcatenated Array  :", sarr, )


Enter the required number for the first list: 1

Enter the required number for the first list: 2

Enter the required number for the first list: 5

Enter the required number for the first list: 9

Enter the required number for the first list: 4

Enter the required number for the Second list: 5

Enter the required number for the Second list: 1

Enter the required number for the Second list: 6

Enter the required number for the Second list: 2

Enter the required number for the Second list: 8


Concatenated Array of Entered Array: [1 2 5 9 4 5 1 6 2 8]


Sorted Array : 
Array 1 : [1 2 4 5 9] 
Array 2 : [1 2 5 6 8] 
Concatenated Array  : [1 1 2 2 4 5 5 6 8 9]


# Question - 3

In [12]:
dim = arr1.ndim 
size = arr1.size # Shows the total number of the elements in the array

print("Array: ", arr1 , "\nIts Number of dimensions: ", dim , "\nIts size: ", size)

Array:  [1 2 5 9 4] 
Its Number of dimensions:  1 
Its size:  5


In [15]:
arr = np.array([ [1,2,1,2,1], [2,3,1,2,1] ])

dim = arr.ndim 
size = arr.size # Shows the total number of the elements in the array

print("Array: ", arr , "\nIts Number of dimensions: ", dim , "\nIts size: ", size)

Array:  [[1 2 1 2 1]
 [2 3 1 2 1]] 
Its Number of dimensions:  2 
Its size:  10


In [19]:
arr = np.array([ [ [1,2,1,2,1], [2,3,1,2,1] ], [ [1,2,1,2,1], [2,3,1,2,1] ]])

dim = arr.ndim 
size = arr.size # Shows the total number of the elements in the array

print("Array: \n", arr , "\nIts Number of dimensions: ", dim , "\nIts size: ", size)

Array: 
 [[[1 2 1 2 1]
  [2 3 1 2 1]]

 [[1 2 1 2 1]
  [2 3 1 2 1]]] 
Its Number of dimensions:  3 
Its size:  20


# Question - 4  

In [31]:
# for example

# 1. Reshape

arr = np.array([2, 3, 1, 3, 5, 7])
print("Shape of the array: " , np.shape(arr))

newarr = arr.reshape(3,2)
print("\nNew Array: \n", newarr)

print("\nShape of the new array: " , np.shape(newarr))

Shape of the array:  (6,)

New Array: 
 [[2 3]
 [1 3]
 [5 7]]

Shape of the new array:  (3, 2)


In [33]:
#2. expand_dims() (Vertical)

arr = np.array([2, 3, 1, 3, 5, 7])
print("Shape of the array: " , np.shape(arr))

newarr = np.expand_dims(arr, axis=0)
print("\nNew Array: \n", newarr)

print("\nShape of the new array: " , np.shape(newarr))

Shape of the array:  (6,)

New Array: 
 [[2 3 1 3 5 7]]

Shape of the new array:  (1, 6)


In [34]:
#2. expand_dims() (Horizontal)

arr = np.array([2, 3, 1, 3, 5, 7])
print("Shape of the array: " , np.shape(arr))

newarr = np.expand_dims(arr, axis=1)
print("\nNew Array: \n", newarr)

print("\nShape of the new array: " , np.shape(newarr))

Shape of the array:  (6,)

New Array: 
 [[2]
 [3]
 [1]
 [3]
 [5]
 [7]]

Shape of the new array:  (6, 1)


In [35]:
#3. newaxis (Horizontal)

arr = np.array([2, 3, 1, 3, 5, 7])
print("Shape of the array: " , np.shape(arr))

newarr = arr[:, np.newaxis]
print("\nNew Array: \n", newarr)

print("\nShape of the new array: " , np.shape(newarr))

Shape of the array:  (6,)

New Array: 
 [[2]
 [3]
 [1]
 [3]
 [5]
 [7]]

Shape of the new array:  (6, 1)


In [36]:
#3. newaxis (Vertical)

arr = np.array([2, 3, 1, 3, 5, 7])
print("Shape of the array: " , np.shape(arr))

newarr = arr[np.newaxis]
print("\nNew Array: \n", newarr)

print("\nShape of the new array: " , np.shape(newarr))

Shape of the array:  (6,)

New Array: 
 [[2 3 1 3 5 7]]

Shape of the new array:  (1, 6)


# Question - 5

In [38]:
arr1 = np.array([1, 4, 9, 16, 25])
arr2 = np.array([36, 49, 64, 81, 100])

print("\nHorizontal: \n", np.hstack((arr1, arr2)))
print("\nVertical : \n", np.vstack((arr1, arr2)))


Horizontal: 
 [  1   4   9  16  25  36  49  64  81 100]

Vertical : 
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Question - 6

In [27]:
arr = np.array([10, 20, 5, 8, 20, 8, 9, 10, 11, 11, 15, 16, 16])

unique, frequency = np.unique(arr, return_counts = True) 

print("Unique Values:", unique) 

print("Frequency Values:", frequency)

arr1 = np.array([unique,frequency])

print("\n", np.sort(arr1).T)

Unique Values: [ 5  8  9 10 11 15 16 20]
Frequency Values: [1 2 1 2 2 1 2 2]

 [[ 5  1]
 [ 8  1]
 [ 9  1]
 [10  2]
 [11  2]
 [15  2]
 [16  2]
 [20  2]]
